### ISSUE TITLE
Invisible warning header text

### ISSUE THREAD

**Issue by thiekus** [catppuccin/gitea#17]
Hi, i have installed your themes and looks awesome! But the problem header text for warning cards is invisible, unless you block select that text. It happens to all variants of theme & I use gitea 1.21.0. Thank you!

![Screenshot 2023-11-19 at 01 38 48](https://github.com/catppuccin/gitea/assets/13563072/7e3cab58-a741-4c70-956d-967a1430644c)

![Screenshot 2023-11-19 at 01 38 33](https://github.com/catppuccin/gitea/assets/13563072/399c274c-10ef-4c7f-b2b5-9dd6e3f2decb)

**Comment by markjoshwel** [comment]
seems like it comes from the catpuccin theme not defining -1 and -2 dark variants, but i doubt that would help \

the base gitea theme uses questionable variables to get the colour

i "fixed" / patched it on my gitea install by find-and replacing `root: {` to `@import("custom.css"); <newline>
root: {
` on all catppuccin theme files with the following content:

```css
blockquote.attention-note {
  border-left-color: var(--color-blue-light);
}
strong.attention-note, svg.attention-note {
  color: var(--color-blue);
}

blockquote.attention-tip {
  border-left-color: var(--color-purple);
}
strong.attention-tip, svg.attention-tip {
  color: var(--color-purple);
}

blockquote.attention-important {
  border-left-color: var(--color-violet);
}
strong.attention-important, svg.attention-important {
  color: var(--color-violet);
}

blockquote.attention-warning {
  border-left-color: var(--color-warning-border);
}
strong.attention-warning, svg.attention-warning {
  color: var(--color-warning-bg);
}

blockquote.attention-caution {
  border-left-color: var(--color-red-light);
}
strong.attention-caution, svg.attention-caution {
  color: var(--color-red);
}
```

and for context, between my patch and the gitea default css as a diff:

```diff
diff --git a/gitea b/catppuccin-fix
index 7d13643..078f5b8 100644
--- a/gitea
+++ b/catppuccin-fix
@@ -1,34 +1,34 @@
 blockquote.attention-note {
-  border-left-color: var(--color-blue-dark-1);
+  border-left-color: var(--color-blue-light);
 }
 strong.attention-note, svg.attention-note {
-  color: var(--color-blue-dark-1);
+  color: var(--color-blue);
 }

 blockquote.attention-tip {
-  border-left-color: var(--color-success-text);
+  border-left-color: var(--color-purple);
 }
 strong.attention-tip, svg.attention-tip {
-  color: var(--color-success-text);
+  color: var(--color-purple);
 }

 blockquote.attention-important {
-  border-left-color: var(--color-violet-dark-1);
+  border-left-color: var(--color-violet);
 }
 strong.attention-important, svg.attention-important {
-  color: var(--color-violet-dark-1);
+  color: var(--color-violet);
 }

 blockquote.attention-warning {
-  border-left-color: var(--color-warning-text);
+  border-left-color: var(--color-warning-border);
 }
 strong.attention-warning, svg.attention-warning {
-  color: var(--color-warning-text);
+  color: var(--color-warning-bg);
 }

 blockquote.attention-caution {
-  border-left-color: var(--color-red-dark-1);
+  border-left-color: var(--color-red-light);
 }
 strong.attention-caution, svg.attention-caution {
-  color: var(--color-red-dark-1);
+  color: var(--color-red);
 }
```

![image](https://github.com/catppuccin/gitea/assets/89562141/f83cd010-c2de-4a51-b38b-9db45d75a20d)

![image](https://github.com/catppuccin/gitea/assets/89562141/c24c733b-bcb6-4c3b-8bed-46c5d3e949e9)
